name: Echo Message Workflow

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message to echo'
        required: true
        default: 'Hello, World!'
        type: string

jobs:
  echo-message:
    runs-on: ubuntu-latest
    steps:
      - name: Echo the message
        run: |
            echo "Message: ${{ github.event.inputs.message }}"